### PR TITLE
Bugfix: Start cutscene when Korgan is not in party

### PR DESCRIPTION
**Pull request by Ychap**

### CODE REVIEW

**Comment by 11jo** [comment]
Hello thanks for your fix !

Don't you think this way will predate the alcool talk and prevent it from happening whether Korgan is in the party or not ?

I propose to [ADD_TRANS_TRIGGER](https://github.com/The-Gate-Project/Alcool/compare/main...Ychap-Fix) to be sure, but it's untested yet, what do you think ?

**Comment by Ychap** [comment]
Hey, thanks for your quick reply!

The additional [ADD_TRANS_TRIGGER](https://github.com/The-Gate-Project/Alcool/compare/main...Ychap-Fix) are not nessesary.

`ADD_TRANS_TRIGGER ARAN 47 ~!InParty("Korgan")~ DO 0` is not needed since the last response is evaluated before.

`ADD_TRANS_TRIGGER ARAN 47 ~!Dead("Korgan") InParty("Korgan")~ DO 1` is already done by [this line](1/files#diff-f2125f0abcfef15b4e6d5082322eb49ae385fb48689dbf6ba9ac5d419e3bde82R18) (and the line before).

\
I have tested this fix in BG2EE/EET with and without Korgan in party, and it worked as you would expect.

**Comment by 11jo** [comment]
I didn't have time to test it today but I will tomorow.

One last question : if another mod also adds a new reply option or trigger, won't the absence of variable be problematic ?

**Comment by Ychap** [comment]
To answer your question:

It will be fine because a new response added by an INTERJECT is appended to the bottom of the response list.
At first the game will evaluate this new response, because responses are evaluated from bottom to top.

**Comment by 11jo** [comment]
Ok, I had time to notice the error and check your correction.

Thank you for answering my questions and for the fix, of course.

**Pull request merged**
